networks:
  mr_watcher_network:

services:
  mr_watcher_tinyproxy:
    build:
      context: ./docker/tinyproxy
    image: mr-watcher-tinyproxy
    container_name: mr-watcher-tinyproxy
    restart: unless-stopped
    ports:
      - ${PROXY_PORT:?err}:${PROXY_PORT:?err}
    environment:
      - BACKEND_BASE_PATH=${BACKEND_BASE_PATH:?err}
      - BACKEND_PORT=${BACKEND_PORT:?err}
      - FRONTEND_PORT=${FRONTEND_PORT:?err}
      - PORT=${PROXY_PORT:?err}
      - BASE_URL=${BASE_URL:?err}
    networks:
      - mr_watcher_network

  mr_watcher_backend:
    build:
      dockerfile: ./Dockerfile
      target: backend
      args:
        - BACKEND_BASE_PATH=${BACKEND_BASE_PATH:?err}
    image: mr-watcher-backend
    container_name: mr-watcher-backend
    restart: unless-stopped
    environment:
      - PORT=${BACKEND_PORT:?err}
      - BASE_PATH=${BACKEND_BASE_PATH:?err}
      - DATABASE_URI=${DATABASE_URI:?err}
    networks:
      - mr_watcher_network

  mr_watcher_frontend:
    build:
      dockerfile: ./Dockerfile
      target: frontend
    image: mr-watcher-frontend
    container_name: mr-watcher-frontend
    restart: unless-stopped
    environment:
      - PORT=${FRONTEND_PORT:?err}
    networks:
      - mr_watcher_network
